server:
  port: 8080
  forward-headers-strategy: native

  servlet:
    session:
      cookie:
        name: JSESSIONID
        secure: true
        http-only: true
        same-site: None
        domain: ${COOKIE_DOMAIN:localhost}
        path: /

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/nutriweek}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  mail:
    api-key: ${BREVO_API_KEY:}
    sender-email: noreply.nutriweek@gmail.com
    sender-name: NutriWeek
  urls:
    verify: http://localhost:8080/auth/verify
    frontendVerified: http://localhost:3000/login
  usda:
    url: https://api.nal.usda.gov/fdc/v1
    key: ${USDA_API_KEY:}
  cors:
    allowed-origins: "http://localhost:3000"
  csrf:
    domain: localhost

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG

