server:
  port: 8080
  forward-headers-strategy: native

  servlet:
    session:
      cookie:
        name: JSESSIONID
        secure: true
        http-only: true
        same-site: None
        domain: ${COOKIE_DOMAIN:localhost}
        path: /

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/nutriweek}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

app:
  mail:
    api-key: ${BREVO_API_KEY:}
    sender-email: ${SENDER_EMAIL:}
    sender-name: NutriWeek
  urls:
    verify: ${USER_VERIFY_URL:http://localhost:8080/auth/verify}
    frontendVerified: ${FRONTEND_VERIFIED_URL:http://localhost:3000/login}
  usda:
    url: https://api.nal.usda.gov/fdc/v1
    key: ${USDA_API_KEY:}
  cors:
    allowed-origins: ${FRONTEND_URL:http://localhost:3000}
  csrf:
    domain: ${COOKIE_DOMAIN:localhost}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.springframework.security: INFO
